---
name: CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  packages: read
  pull-requests: write

env:
  ENV_NAME: DEMO
  REGION: eu-central-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REPOSITORY_OWNER: ${GITHUB_REPOSITORY_OWNER}
  CI: false
  REGISTRY: ${{ vars.REGISTRY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Use npm packages cache
        uses: actions/cache@v4
        with:
          path: |
            app/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-npm

#      - name: Deploy to AWS
#        run: ./deploy.sh
#        env:
#          ENV_NAME: ${{ env.ENV_NAME }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .
          push: true
          tags: ${{ env.REGISTRY }}/frontend:${{ github.sha }}
          provenance: false