---
name: CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  ENV_NAME: DEMO
  REGION: eu-central-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REPOSITORY_OWNER: ${GITHUB_REPOSITORY_OWNER}
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use npm packages cache
        uses: actions/cache@v4
        with:
          path: |
            app/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-npm
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Deploy to AWS
        run: ./deploy.sh
        env:
          ENV_NAME: ${{ env.ENV_NAME }}